[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiosqlite>=0.19.0",
    "chardet>=5.2.0",
    "dishka>=1.7.2",
    "fastapi>=0.121.1",
    "gigachat>=0.1.43",
    "hf-xet>=1.2.0",
    "langchain>=1.0.5",
    "langchain-text-splitters>=1.0.0",
    "numpy>=2.3.4",
    "ollama>=0.6.0",
    "openai>=2.8.0",
    "pandas>=2.3.3",
    "pdfplumber>=0.11.8",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.21",
    "qdrant-client>=1.15.1",
    "result>=0.17.0",
    "retry>=0.9.2",
    "sentence-transformers>=5.1.2",
    "sqlalchemy>=2.0.45",
    "torch>=2.9.0",
    "transformers>=4.57.1",
    "uvicorn>=0.38.0",
]

[dependency-groups]
dev = [
    "mypy>=1.19.0",
    "pytest>=9.0.2",
    "pytest-cov>=6.0.0",
    "pytest-asyncio>=1.0.0",
    "httpx>=0.28.0",
    "ruff>=0.14.8",
]

[tool.ruff]
line-length = 100
target-version = "py311"

exclude = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "tests",
    "data",
]

[tool.ruff.lint]
select = ["E", "W", "F", "I", "B"]
ignore = []
fixable = ["ALL"]

[tool.ruff.format]
quote-style = "double"

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
files = ["src"]
no_implicit_optional = true

[tool.pytest.ini_options]
pythonpath = [".", "src"]
testpaths = ["tests"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
addopts = [
    "-v",
    "--cov=src",
    "--cov-report=term-missing",
    "--cov-report=html:htmlcov",
    "--cov-fail-under=65"
]

[tool.coverage.run]
source = ["src"]
omit = [
    "src/**/__init__.py",
    "src/**/__pycache__/*",
]
branch = true

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise NotImplementedError",
    "if TYPE_CHECKING:",
    "if __name__ == .__main__.:",
    "@abstractmethod",
]
show_missing = true
